Create a fragment
KirillAle/CurrencyRepo pull request #5
Opened 2023-12-08 11:03 UTC by KirillAle

added navigation
added fragment of currency list screen

2023-12-08 12:13 UTC, iamthevoid requested changes

2023-12-08 12:13 UTC, iamthevoid commented on app/build.gradle
> +        viewBinding.enable true
Не используешь, а добавил )

2023-12-08 12:13 UTC, iamthevoid commented on app/src/main/java/com/example/currency/MainActivity.kt
> +        setContentView(R.layout.fragment_currency_list)
Всё ещё не тот лейаут

2023-12-08 12:13 UTC, iamthevoid commented on app/src/main/res/layout/fragment_currency_list.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
На самом деле можно обойтись LinearLayout. Вес выстави RecyclerView и он щаймёт всё пространство. Констрейнт тяжелее, его использвоть нужно по необходимости

2023-12-08 12:13 UTC, iamthevoid commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Лишнее

2023-12-09 12:28 UTC, KirillAle commented on app/src/main/java/com/example/currency/MainActivity.kt
> +        setContentView(R.layout.fragment_currency_list)
странно, но у меня в лэйауте написан activity main

2023-12-09 12:38 UTC, KirillAle commented on app/src/main/res/layout/fragment_currency_list.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
поменял, вес поставил

2023-12-09 12:39 UTC, KirillAle commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
убрл

2023-12-09 12:42 UTC, KirillAle commented on app/src/main/res/layout/fragment_currency_list.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
блин, не знаю как так, но с линером реально быстрее работает. даже видно. может показалось, но как будто видно

2023-12-09 14:03 UTC, merged